name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: mnist_classifier
        tags: ${{ env.RELEASE_VERSION }}
        registry: ghcr.io
        dockerfile: Dockerfile
        directory: .
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN}}
        addLatest: true
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: Clone config
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN}}
        repository: kimjunil/mlops_mnist_config
        path: mlops_mnist_config
    - name: Clone config
      run: |
        cd mlops_mnist_config/overlays/dev \
        kustomize edit set image kimjunil/mnist_classifier:${{ env.RELEASE_VERSION }} \
        git commit -am 'Publish new version ${imageTag} to dev' \
        git push || echo 'no changes'
      
